fix: adjusted layout and remove variables dont used
nfewizard-org/nfewizard-io pull request #14
Opened 2024-08-28 17:24 UTC by dliocode

* As informações de CPF/CNPJ do emitente, destinatário e transportadora na hora de gerar a DANFE vem de outras tags.

* Ajustado o layout de algumas informações da transportadora.

* Removido variáveis não utilizadas.

2024-08-28 17:47 UTC, dliocode commented
Ao gerar a danfe, as informações de CPF/CNPJ do emitente, destinatário e transportadora não estavam sendo exibidos.

Isso porque não existe as keys CNPJCPF, no retorno da autorização da NFE.
Foi necessário fazer essa alteração.

![image](https://github.com/user-attachments/assets/360a1d38-496a-4397-95f7-b53dbad6e0f1)

2024-09-05 20:42 UTC, Maurelima reviewed
A alteração é pertinente, porém impactará na autorização NFe (que utiliza a tag CNPJCPF). 

Estarei avaliando mais a fundo o impacto gerado e retorno.

2024-09-12 11:52 UTC, Maurelima requested changes
@dliocode, pode fazer uma alteração na parte da exibição do CNPJCPF? 

Como existe uma tratativa na emissão de NFe para o campo CNPJCPF seria interessante mante-lo como um campo possível na geração da DANFE.

`const documento = this.documento.mascaraCnpjCpf(this.emit.CNPJ || this.emit.CPF)`
Ficaria assim:
`const documento = this.documento.mascaraCnpjCpf(this.emit.CNPJCPF || this.emit.CNPJ || this.emit.CPF)`

2024-09-12 12:03 UTC, dliocode commented
Ajustado

2024-09-12 12:21 UTC, merged